requires 'Mojolicious', 4.19;
requires 'Mojolicious::Plugin::Authentication', 1.24;
requires 'Compress::Zlib';
requires 'XML::Simple';
requires 'DBIx::Class';
requires 'DBD::mysql';
requires 'Digest::Bcrypt';
requires 'Mojo::Redis', 0.9903;
requires 'DBIx::Class::Tree::AdjacencyList';
requires 'Net::DNS';
requires 'JSON::XS';
requires 'Gearman::Client';
requires 'DateTime';
require 'IO::All';
