#requires 'Mojolicious', 4.19;
requires 'Mojolicious';
#requires 'Mojolicious::Plugin::Authentication', 1.24;
requires 'DBIx::Class::Tree::NestedSet';
#requires 'Mojolicious::Plugin::Authentication';
requires 'Mojolicious::Plugin::HttpBasicAuth';
requires 'Compress::Zlib';
requires 'XML::Simple';
requires 'DBIx::Class';
requires 'DBD::mysql';
requires 'Digest::Bcrypt';
#requires 'Mojo::Redis', '>= 0.9903, < 0.9904';
requires 'Mojo::Redis';
#requires 'DBIx::Class::Tree::AdjacencyList';
requires 'Net::DNS';
requires 'JSON::XS';
#requires 'Gearman::Client';
requires 'DateTime';
requires 'IO::All';
requires 'IPC::Lite';
requires 'DBD::SQLite';
requires 'DBIx::Class::DeploymentHandler';
requires 'DBIx::Class';